name: VyOS LTS Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      # For VyOS 1.2 (crux) use vyos/vyos-build:crux
      # For VyOS 1.3 (equuleus) use vyos/vyos-build:equuleus
      # For our VyOS rolling release you should use vyos/vyos-build which will always refer to the latest image.
      # Ref: https://docs.vyos.io/en/latest/contributing/build-vyos.html#build
      image: vyos/vyos-build:equuleus
      env:
        TZ: America/Chicago
      options: --privileged

    steps:
    - name: Set env
      run: |
        echo "RELEASE_VERSION=LTS" >> $GITHUB_ENV 

    - name: git clone vyos-build
      run: |
        set -eux
        
        git clone -b equuleus --single-branch https://github.com/vyos/vyos-build
        cd vyos-build
        ./configure \
          --architecture amd64 \
          --build-by bartei81@gmail.com \
          --build-type release \
          --version ${{ env.RELEASE_VERSION }}
        make iso
        make qemu

    - name: ls
      run: |
        set -eux

        pwd
        ls -lah
        ls -lah vyos-build/build

#    - uses: actions/create-release@master
#      id: create_release # ファイルアップロードに outputs の値を使用するため ID が必要
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        tag_name: ${{ github.ref }}
#        release_name: VyOS ${{ github.ref }} LTS
#        body: |
#          VyOS ${{ env.RELEASE_VERSION }} LTS
#        draft: true
#        prerelease: true

#    - uses: actions/upload-release-asset@master
#      env:
#        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#      with:
#        upload_url: ${{ steps.create_release.outputs.upload_url }}
#        asset_path: vyos-build/build/vyos-${{ env.RELEASE_VERSION }}-amd64.iso
#        asset_name: vyos-${{ env.RELEASE_VERSION }}-amd64.iso
#        asset_content_type: application/x-iso9660-image

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.PAT_TOKEN }}
        tag_name: "v${{ env.RELEASE_VERSION }}"
        generate_release_notes: false
        files: |
          vyos-build/build/vyos-${{ env.RELEASE_VERSION }}-amd64.iso