name: VyOS Equuleus Build

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    container:
      # For VyOS 1.2 (crux) use vyos/vyos-build:crux
      # For VyOS 1.3 (equuleus) use vyos/vyos-build:equuleus
      # For our VyOS rolling release you should use vyos/vyos-build which will always refer to the latest image.
      # Ref: https://docs.vyos.io/en/latest/contributing/build-vyos.html#build
      image: vyos/vyos-build:sagitta
      env:
        TZ: America/Chicago
      options: --privileged

    steps:
    - name: Set env
      run: |
        echo "RELEASE_VERSION=${{ github.sha }}" >> $GITHUB_ENV 

    - name: git clone vyos-build
      run: |
        set -eux
        
        git clone -b sagitta --single-branch https://github.com/vyos/vyos-build
        cd vyos-build
        mkdir -p build/vyos-refs/heads
        ./configure \
          --architecture amd64 \
          --build-by bartei81@gmail.com \
          --build-type release \
          --version ${{ env.RELEASE_VERSION }}
        make iso

    - name: ls
      run: |
        set -eux

        pwd
        ls -lah
        ls -lahR vyos-build/build

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.PAT_TOKEN }}
        tag_name: "v${{ env.RELEASE_VERSION }}"
        generate_release_notes: false
        files: |
          vyos-build/build/vyos-${{ env.RELEASE_VERSION }}-amd64.iso
