name: VyOS LTS nightly build

on:
#  schedule:
#    - cron: "0 0 * * *"

  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: Set VyOS version
        id: set_vyos_version
        run: |
          echo "VYOS_VERSION=equuleus-$(date -u +%Y%m%d%H%M)" >> $GITHUB_ENV

      - uses: actions/checkout@v3

      - name: Git clone vyos-build
        run: git clone -b equuleus --single-branch https://github.com/vyos/vyos-build

      - name: Build openstack
        run: |
          docker run \
          --rm --privileged \
          -v ./vyos-build/:/vyos \
          -w /vyos vyos/vyos-build:equuleus \
          sudo make openstack

      - name: List Contents
        run: |
          ls ./vyos-build/build
